### PR TITLE
Fix fuse3-libs package repo on EL8 when building for singcvmfs

### PR DESCRIPTION
**Pull request by natefoo**

### CODE REVIEW

**Comment by DrDaveD** [comment]
Thanks, Nate.  Please add a line at the top of the ChangeLog of what is changed.  

Let me know if you also want a new tagged release to go with this.

**Comment by natefoo** [comment]
Thanks! Done. No need to release - I am trying to get this working with some weird containers and may have a couple other changes to propose.

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
By the way I don't know of anybody who has decided that singcvmfs is really what they want to use in production.  I think the "Cache considerations" note in the README ends up getting in the way.  More people are using mode 3 or mode 1.

**Comment by natefoo** [comment]
Thanks for the heads up. I am essentially doing mode 1 already (albeit with my own scripts), using an alien cache on HPC scratch, and it works well enough. Our usage may not be high enough to really hit the fs.

Mode 3 would be a nice improvement, but singcvmfs would give the added benefit of not needing to do any path manipulation between `/cvmfs/...` and the unprivileged mount. I do manipulate paths currently but the way it's implemented, it will run into problems on shared partitions where multiple jobs might land on the same node at the same time.

**Pull request merged**
